### ISSUE TITLE
Doc: convert site documentation to dox

### ISSUE THREAD

**Issue by jason-braun-sociomantic-mouse** [sociomantic-tsunami/microbe#82]
right now we use docker to generate the www/ docs.  Dox generates a json file from the comments, leaving us to format them ourselves.  a better but more involved option.
https://www.npmjs.com/package/dox

right now:
microbe uses docker

desired:
generate json that fits into a template

for #81

**Comment by leandro-lucarella-sociomantic** [comment]
Closing as this project is going to be archived.
